[project]
name = "jentic-openapi-validator"
version = "0.1.0"
description = "Jentic OpenAPI Validator"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
  "jentic-openapi-transformer",
  "jentic-openapi-parser",
  "openapi-spec-validator",
  "lsprotocol"
]

[project.optional-dependencies]
spectral = ["jentic-openapi-validator-spectral"]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv.sources]
jentic-openapi-transformer = { workspace = true }
jentic-openapi-parser      = { workspace = true }
jentic-openapi-validator-spectral      = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

