[project]
name = "jentic-openapi-parser"
version = "0.1.0"
description = "Jentic OpenAPI Parser"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.11"
dependencies = [
    "attrs~=25.4",
    "jentic-openapi-common~=0.1.0",
    "pyyaml~=6.0",
    "requests~=2.32",
    "ruamel-yaml~=0.18"
]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv]
package = true

[tool.uv.build-backend]
namespace = true
module-name = "jentic.apitools.openapi.parser"
module-root = "src/"

[tool.uv.sources]
jentic-openapi-common = { workspace = true }

[build-system]
requires = ["uv_build~=0.8.15"]
build-backend = "uv_build"

[project.entry-points."jentic.apitools.openapi.parser.backends"]
base = "jentic.apitools.openapi.parser.backends.base:BaseParserBackend"
pyyaml = "jentic.apitools.openapi.parser.backends.pyyaml:PyYAMLParserBackend"
ruamel-safe = "jentic.apitools.openapi.parser.backends.ruamel_safe:RuamelSafeParserBackend"
ruamel-roundtrip = "jentic.apitools.openapi.parser.backends.ruamel_roundtrip:RuamelRoundTripParserBackend"

