[project]
name = "jentic-openapi-parser"
version = "0.1.0"
description = "Jentic OpenAPI Parser"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = []

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

