[project]
name = "jentic-openapi-validator-spectral"
version = "0.1.0"
description = "Jentic OpenAPI Spectral Validator Strategy"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
  "jentic-openapi-validator",
  "lsprotocol",
  "importlib-resources>=1.3.0;python_version<'3.9'"
]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv.sources]
jentic-openapi-validator = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."jentic.openapi_validator_strategies"]
spectral = "jentic_openapi_validator_spectral.spectral_validator:SpectralValidator"

[tool.setuptools.package-data]
"jentic_openapi_validator_spectral" = ["rulesets/*.yaml", "rulesets/*.yml"]
