[project]
name = "jentic-openapi-validator-spectral"
version = "0.1.0"
description = "Jentic OpenAPI Spectral Validator Backend"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.11"
dependencies = [
  "jentic-openapi-common",
  "jentic-openapi-validator",
  "lsprotocol"
]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv]
package = true

[tool.uv.build-backend]
namespace = true
module-name = "jentic.apitools.openapi.validator.backends.spectral"
module-root = "src/"

[tool.uv.sources]
jentic-openapi-common = { workspace = true }
jentic-openapi-validator = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."jentic.apitools.openapi.validator.backends"]
spectral = "jentic.apitools.openapi.validator.backends.spectral:SpectralValidatorBackend"

[tool.setuptools.package-data]
"jentic.apitools.openapi.validator.backends.spectral" = ["rulesets/*.yaml", "rulesets/*.yml"]
