[project]
name = "jentic-openapi-bundler-redocly"
version = "0.1.0"
description = "Jentic OpenAPI Redocly Bundler Strategy"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
  "jentic-openapi-common",
  "jentic-openapi-transformer",
  "importlib-resources>=1.3.0;python_version<'3.9'"
]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv.sources]
jentic-openapi-transformer = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."jentic.openapi_bundler_strategies"]
redocly = "jentic_openapi_bundler_redocly.redocly_bundler:RedoclyBundler"


