repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
      - id: ruff-format
        args: [--check, --diff]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.18
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false