[project]
name = "jentic-openapi-transformer"
version = "0.1.0"
description = "Jentic OpenAPI Transformer"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = ["jentic-openapi-parser"]

[tool.uv]
package = true

[tool.uv.build-backend]
namespace = true

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[project.optional-dependencies]
redocly = ["jentic-openapi-transformer-redocly"]

[tool.uv.sources]
jentic-openapi-parser = { workspace = true }
jentic-openapi-transformer-redocly = { workspace = true }


[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

