[project]
name = "jentic-openapi-transformer-redocly"
version = "0.1.0"
description = "Jentic OpenAPI Redocly Transformer Strategy"
readme = "README.md"
authors = [{ name = "Jentic", email = "hello@jentic.com" }]
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
requires-python = ">=3.11"
dependencies = [
  "jentic-openapi-common",
  "jentic-openapi-transformer",
  "importlib-resources>=1.3.0;python_version<'3.9'"
]

[project.optional-dependencies]
test = [
  "pytest",
]

[project.urls]
Homepage = "https://github.com/jentic/jentic-openapi-tools"

[tool.uv]
package = true

[tool.uv.build-backend]
namespace = true
module-name = "jentic.apitools.openapi.transformer.redocly"
module-root = "src/"

[tool.uv.sources]
jentic-openapi-common = { workspace = true }
jentic-openapi-transformer = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."jentic.apitools.openapi.transformer.strategies"]
redocly = "jentic.apitools.openapi.transformer.redocly:RedoclyBundler"


